#!/bin/bash
set -e

# ============================================================
# Postfix 容器入口脚本
# - 动态从数据库加载域名到 virtual_domains
# - 配置 catch-all 收件
# ============================================================

echo "==> Starting Postfix mail receiver..."

# 设置权限
chmod +x /usr/local/bin/mail-receiver

API_URL="${API_URL:-http://api:8967}"

# 生成初始虚拟域名列表（regexp map，可为空）
cat > /etc/postfix/virtual_domains << 'MAP'
# Auto-generated by entrypoint.sh
MAP

# 定期从 API 拉取域名列表的 cron 脚本
cat > /usr/local/bin/sync-domains.sh << 'SCRIPT'
#!/bin/bash
# 从 API 获取域名列表并更新 Postfix 虚拟域名
# ★ API_URL 默认为 http://api:8967，可通过环境变量覆盖。
API_URL="${API_URL:-http://api:8967}"
DOMAINS=$(curl -sf "${API_URL}/internal/domains" 2>/dev/null || echo "")
if [ -n "$DOMAINS" ]; then
    echo "$DOMAINS" | python3 -c "
import json, re, sys
data = json.load(sys.stdin)
lines = ['# Auto-generated by sync-domains.sh']
for d in data.get('domains', []):
    if d.get('is_active', False):
        domain = (d.get('domain') or '').strip().lower()
        if not domain:
            continue
        if domain.startswith('*.'):
            base = re.escape(domain[2:])
            lines.append(f'/^([^.]+\\\\.)+{base}$/ OK')
        else:
            lines.append(f'/^{re.escape(domain)}$/ OK')
print('\\n'.join(lines))
" > /etc/postfix/virtual_domains.new
    if [ -f /etc/postfix/virtual_domains.new ]; then
        mv /etc/postfix/virtual_domains.new /etc/postfix/virtual_domains
        postfix reload 2>/dev/null || true
    fi
fi
SCRIPT
chmod +x /usr/local/bin/sync-domains.sh

# 启动前先同步一次域名规则
/usr/local/bin/sync-domains.sh || true

# 启动 cron 定期同步域名（每 60 秒）
(while true; do sleep 60; /usr/local/bin/sync-domains.sh; done) &

# 更新 main.cf 中的主机名/域名（由环境变量 SMTP_HOSTNAME 注入）
POSTFIX_HOSTNAME="${SMTP_HOSTNAME:-mail.example.com}"
POSTFIX_DOMAIN="${POSTFIX_HOSTNAME#*.}"
if [ -z "$POSTFIX_DOMAIN" ] || [ "$POSTFIX_DOMAIN" = "$POSTFIX_HOSTNAME" ]; then
    POSTFIX_DOMAIN="example.com"
fi

postconf -e "myhostname=${POSTFIX_HOSTNAME}"
postconf -e "mydomain=${POSTFIX_DOMAIN}"
postconf -e 'myorigin=$mydomain'
postconf -e "virtual_mailbox_domains=regexp:/etc/postfix/virtual_domains"
postconf -e "virtual_transport=mailreceiver:"

# 启动 Postfix（前台运行）
exec postfix start-fg
